Repository racket/racket, pull requests merged in 2019-12, with the labels that each got.

#2944 More complete set of tests in Actions
  .github/workflows/ci-push.yml
Labels: ci

#2945 Actions for Windows CI
  .github/workflows/ci-push.yml
Labels: ci

#2948 Remove support for azure-pipelines
  .azure-pipelines.yml
Labels: ci

#2949 Remove AppVeyor pipeline
  .appveyor.yml
Labels: ci

#2952 Correct which racket is built for CS bootstrap
  racket/src/worksp/README.txt
Labels: documentation

#2959 On Linux build with clang as well
  .github/workflows/ci-push.yml
Labels: ci

#2901 Revert "Fix gen:dict methods for alists with duplicate keys (#2846)"
  pkgs/racket-test/tests/generic/alist.rkt
  racket/collects/racket/private/dict.rkt
Labels: regression

#2990 RacketCS skips loading <init-lib> when given -v flag while Racket does load <init-lib>
  racket/src/cs/main.sps
Labels: racket-cs
