Repository racket/racket, pull requests merged in 2020-12, with the labels that each got.

#3538 Add an example of how to use in-indexed
  pkgs/racket-doc/scribblings/reference/sequences.scrbl
Labels: documentation

#3543 Fix bug in example for in-indexed
  pkgs/racket-doc/scribblings/reference/sequences.scrbl
Labels: documentation

#3545 Clarify use of build-path/convention-type in scribble docs (fixes #3424)
  pkgs/racket-doc/scribblings/reference/paths.scrbl
Labels: documentation

#3556 Format the name of continuation prompt tags
  pkgs/racket-doc/scribblings/reference/cont.scrbl
  pkgs/racket-doc/scribblings/reference/struct-inspectors.scrbl
  pkgs/racket-test-core/tests/racket/prompt.rktl
  racket/src/bc/src/fun.c
  racket/src/cs/rumble/control.ss
  racket/src/cs/schemified/io.scm
  racket/src/io/print/main.rkt
Labels: racket-cs

#3563 Add syntax tests for other configurations.
  .github/workflows/ci-push-arm_linux.yml
  .github/workflows/ci-push-x86_linux.yml
  .github/workflows/ci-push_macos.yml
  .github/workflows/ci_win.yml
Labels: ci

#3550 CI: prevent forks from running jobs for self-hosted
  .github/workflows/PR_ARM32-fastbuild.yml
  .github/workflows/PR_ARM64-fastbuild.yml
  .github/workflows/chez-build.yml
  .github/workflows/ci-push-arm_linux.yml
  .github/workflows/ubsan-arm.yml
Labels: ci

#3573 Split the testing steps in the Windows CI workflow
  .github/workflows/ci_win.yml
Labels: ci

#3580 docs: fix upper ASCII limit for control characters
  pkgs/racket-doc/scribblings/guide/regexp.scrbl
Labels: documentation

#3587 Foreign functions: on Windows, retrieve _errno from MSVCRT
  racket/src/cs/rumble/foreign.ss
Labels: bug, racket-cs

#3596 Install local package catalog in Windows CI
  .github/workflows/ci_win.yml
  pkgs/racket-test/tests/xml/test.rkt
Labels: ci
