Repository racket/racket, pull requests merged in 2020-10, with the labels that each got.

#3202 Add more examples to I/O Patterns in the Guide
  pkgs/racket-doc/scribblings/guide/io.scrbl
Labels: PR-good-to-merge

#3427 Fix compiler warning in 32bits due to size mismatch in ptr cast
  racket/src/ChezScheme/c/gcwrapper.c
Labels: bug, racket-cs

#3447 replace add-path with GITHUB_ENV
  .github/workflows/ci-asan.yml
  .github/workflows/ci-ubsan.yml
Labels: ci

#3294 CI support on self-hosted arm runners
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push-arm_linux.yml
  .github/workflows/ci-push-x86_linux.yml
  .github/workflows/ubsan-arm.yml
  .github/workflows/ubsan-x86.yml
Labels: ci

#3461 Use locale.h if not xlocale.h header
  racket/src/rktio/rktio_private.h
Labels: bug, racket-bc

#3463 Do not run ARM tests on PR
  .github/workflows/ci-pr-arm_fastbuild.yml
  .github/workflows/ci-push-arm_linux.yml
  .github/workflows/ubsan-arm.yml
Labels: ci

#3466 Fix CFLAGS ordering to ensure users CFLAGS take precedence
  racket/src/ChezScheme/c/Mf-a6fb
  racket/src/ChezScheme/c/Mf-a6le
  racket/src/ChezScheme/c/Mf-a6nb
  racket/src/ChezScheme/c/Mf-a6ob
  racket/src/ChezScheme/c/Mf-a6osx
  racket/src/ChezScheme/c/Mf-a6s2
  racket/src/ChezScheme/c/Mf-arm32le
  racket/src/ChezScheme/c/Mf-arm64le
  racket/src/ChezScheme/c/Mf-i3fb
  racket/src/ChezScheme/c/Mf-i3le
  racket/src/ChezScheme/c/Mf-i3nb
  racket/src/ChezScheme/c/Mf-i3ob
  racket/src/ChezScheme/c/Mf-i3osx
  racket/src/ChezScheme/c/Mf-ppc32le
Labels: bug, racket-cs
