Repository racket/racket, pull requests merged in 2020-07, with the labels that each got.

#3292 Clarify that synchronizing on a semaphore decrements its counter
  pkgs/racket-doc/scribblings/reference/semaphores.scrbl
Labels: documentation

#3289 win32: add Power Shell script to set env vars
  racket/src/worksp/README.txt
  racket/src/worksp/msvcprep.ps1
Labels: PR-good-to-merge

#2091 Support -l for raco make.
  pkgs/compiler-lib/compiler/commands/make.rkt
  pkgs/compiler-test/tests/compiler/make.rkt
  pkgs/racket-doc/scribblings/raco/make.scrbl
Labels: PR-good-to-merge

#3303 If CI is running on release branch, use Chez release
  .github/workflows/ci-push_linux.yml
Labels: ci

#3313 Fix typos
  pkgs/racket-doc/scribblings/guide/char-strings.scrbl
Labels: documentation

#3316 Solo Chez build/test workflow
  .github/scripts/matting.sh
  .github/scripts/summary
  .github/scripts/test.sh
  .github/workflows/chez-build.yml
  racket/src/ChezScheme/.github/scripts/build.sh
  racket/src/ChezScheme/.github/workflows/build.yml
Labels: ci, racket-cs

#3322 Speed up solo chez testing
  .github/scripts/test.sh
Labels: ci
