Repository racket/racket, pull requests merged in 2020-05, with the labels that each got.

#3152 Only create snapshots when action is ran from main repo
  .github/workflows/ci-snapshot.yml
Labels: ci

#3157 Move static analysis jobs to their own CI file to split workflows
  .github/workflows/ci-push.yml
  .github/workflows/scanbuild_static-analysis.yml
Labels: ci

#3160 Remove gitlab CI
  .github/workflows/DockerImages/Dockerfile.builddeps
  .github/workflows/DockerImages/Dockerfile.testdeps
  .github/workflows/DockerImages/Makefile
  .github/workflows/DockerImages/README.md
  .gitlab-ci.yml
  .gitlab/build-test.sh
Labels: ci

#3159 Add workflow to test racket with sanitizers
  .github/workflows/ci-ubsan.yml
Labels: ci

#3166 Fail when ubsan finds failures
  .github/workflows/ci-ubsan.yml
Labels: ci

#3164 add link to https://racket-lang.org/friendly.html
  README.md
Labels: documentation

#3169 Add future tests to CI
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push.yml
  .github/workflows/ci-ubsan.yml
Labels: ci

#3170 Add precise annotations to improve scanbuild
  .github/workflows/scanbuild_static-analysis.yml
Labels: ci

#3178 Ensure that the GMP ARM extra file has the correct extension
  racket/src/cfg-racket
  racket/src/racket/configure.ac
  racket/src/racket/gc2/Makefile.in
  racket/src/racket/src/Makefile.in
Labels: bug

#3175 Add future tests to CI
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push.yml
  .github/workflows/ci-ubsan.yml
  pkgs/racket-test/tests/future/vector-limit.rkt
Labels: ci

#3200 Add initial LGTM configuration for Racket
  .lgtm.yml
Labels: ci

#3206 Build Docker Images from GitHub Actions
  .github/workflows/docker-racketci-builddeps.yml
  .github/workflows/docker-racketci-testdeps.yml
Labels: ci

#3209 Only rebuild docker images if changes are done in master branch
  .github/workflows/docker-racketci-builddeps.yml
  .github/workflows/docker-racketci-testdeps.yml
Labels: ci

#3218 Non-split build/test workflow on Windows10 for push commits
  .github/workflows/ci-push_win.yml
Labels: ci

#3220 Improve Windows CI Testing
  .github/workflows/ci-pr.yml
  .github/workflows/ci_win.yml
Labels: ci
