Repository racket/racket, pull requests merged in 2020-08, with the labels that each got.

#3327 Fix target names post-CS becoming the default
  .github/workflows/ci-ubsan.yml
Labels: ci

#3328 Fix tool name in SARIF files depending on racket build mode
  .github/scripts/adjust-sarif-tool.sh
  .github/workflows/scanbuild_static-analysis.yml
Labels: ci

#3337 Fix variable replacement
  racket/src/ChezScheme/c/Mf-arm32le
Labels: regression

#3341 Remove dead store identified by a static analyzer
  racket/src/bc/src/print.c
Labels: racket-bc

#3347 pkg: deduplicate dependency list for install command
  racket/collects/pkg/private/install.rkt
Labels: package system
