Repository racket/racket, pull requests merged in 2021-05, with the labels that each got.

#3812 Improve documentation for hash update functions
  pkgs/racket-doc/scribblings/reference/hashes.scrbl
Labels: documentation

#3748 Implementation of 3x3 and 4x4 Toom-Cook multiplication.
  racket/src/ChezScheme/mats/5_3.ms
  racket/src/ChezScheme/s/5_3.ss
Labels: performance

#3829 Fix warning about `git checkout HEAD^2`
  .github/workflows/codeql-analysis.yml
Labels: ci
