Repository racket/racket, pull requests merged in 2021-01, with the labels that each got.

#3601 Fix typo and trailing whitespace in box-cas! docs
  pkgs/racket-doc/scribblings/reference/data.scrbl
Labels: documentation

#3599 list: optimize in-combinations and combinations
  racket/collects/racket/list.rkt
Labels: performance

#3594 doc: elaborate the behavior of datum->syntax
  pkgs/racket-doc/scribblings/reference/stx-ops.scrbl
Labels: documentation

#3629 ci: cross-compile to iOS for PR
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push_macos.yml
Labels: ci

#3651 cs: add pariah for slow path of define-inline
  racket/src/cs/rumble/inline.ss
Labels: performance
