Repository racket/racket, pull requests merged in 2023-02, with the labels that each got.

#4564 ci: fix warnings
  .github/workflows/chez-build.yml
  .github/workflows/ci-asan.yml
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push-x86_linux.yml
  .github/workflows/ci-push_macos.yml
  .github/workflows/ci-snapshot.yml
  .github/workflows/ci_win.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-racketci.yml
  .github/workflows/scanbuild_static-analysis.yml
  .github/workflows/scribble_build-guide.yml
  .github/workflows/scribble_license.yml
  .github/workflows/ubsan-x86.yml
Labels: ci

#4533 doc: Add examples of `custodian-limit-memory`
  pkgs/racket-doc/scribblings/reference/custodians.scrbl
  pkgs/racket-doc/scribblings/reference/threads.scrbl
Labels: documentation

#4562 fix random docs
  pkgs/racket-doc/scribblings/reference/numbers.scrbl
Labels: documentation

#4555 match: speed up vector pattern matching with one ddk
  pkgs/racket-test/tests/match/examples.rkt
  racket/collects/racket/match/parse.rkt
Labels: performance

#4582 Chez Scheme; Add more reductions for if and eq? in cp0
  racket/src/ChezScheme/mats/cp0.ms
  racket/src/ChezScheme/s/cp0.ss
Labels: racket-cs
