Repository racket/racket, pull requests merged in 2023-10, with the labels that each got.

#4783 docs: correct typos in `keyword-apply`
  pkgs/racket-doc/scribblings/reference/procedures.scrbl
Labels: documentation

#4801 doc: correct unsafe-unbox/set-box! signature
  pkgs/racket-doc/scribblings/reference/unsafe.scrbl
Labels: documentation, PR-good-to-merge

#4800 match: fix box pattern
  pkgs/racket-test/tests/match/examples.rkt
  racket/collects/racket/match/compiler.rkt
Labels: PR-good-to-merge, bug
