Repository racket/racket, pull requests merged in 2023-11, with the labels that each got.

#4809 docs: minor corrections to Networking Libraries reference
  pkgs/net-doc/net/scribblings/common.rkt
  pkgs/net-doc/net/scribblings/git-checkout.scrbl
  pkgs/net-doc/net/scribblings/http-client.scrbl
  pkgs/net-doc/net/scribblings/sendurl.scrbl
  pkgs/net-doc/net/scribblings/smtp.scrbl
  pkgs/net-doc/net/scribblings/url.scrbl
Labels: documentation

#4808 docs: update old-fashioned contracts
  pkgs/net-doc/net/scribblings/cgi.scrbl
  pkgs/net-doc/net/scribblings/cookie.scrbl
  pkgs/net-doc/net/scribblings/dns.scrbl
  pkgs/net-doc/net/scribblings/ftp.scrbl
  pkgs/net-doc/net/scribblings/head.scrbl
  pkgs/net-doc/net/scribblings/http-client.scrbl
  pkgs/net-doc/net/scribblings/mime.scrbl
  pkgs/net-doc/net/scribblings/pop3.scrbl
  pkgs/net-doc/net/scribblings/sendmail.scrbl
  pkgs/net-doc/net/scribblings/sendurl.scrbl
  pkgs/net-doc/net/scribblings/smtp.scrbl
  pkgs/net-doc/net/scribblings/ssl-tcp-unit.scrbl
  pkgs/net-doc/net/scribblings/tcp.scrbl
  pkgs/net-doc/net/scribblings/uri-codec.scrbl
  pkgs/net-doc/net/scribblings/url.scrbl
  pkgs/racket-doc/dynext/dynext.scrbl
  pkgs/racket-doc/file/scribblings/gzip.scrbl
  pkgs/racket-doc/file/scribblings/ico.scrbl
  pkgs/racket-doc/scribblings/foreign/com-auto.scrbl
  pkgs/racket-doc/scribblings/foreign/pointers.scrbl
  pkgs/racket-doc/scribblings/foreign/types.scrbl
  pkgs/racket-doc/scribblings/guide/contracts/general-function.scrbl
  pkgs/racket-doc/scribblings/raco/api.scrbl
  pkgs/racket-doc/scribblings/raco/bundle-api.scrbl
  pkgs/racket-doc/scribblings/raco/dist-api.scrbl
  pkgs/racket-doc/scribblings/raco/exe-api.scrbl
  pkgs/racket-doc/scribblings/raco/launcher.scrbl
  pkgs/racket-doc/scribblings/raco/make.scrbl
  pkgs/racket-doc/scribblings/raco/plt.scrbl
  pkgs/racket-doc/scribblings/raco/unpack.scrbl
  pkgs/racket-doc/scribblings/reference/chaperones.scrbl
  pkgs/racket-doc/scribblings/reference/syntax-util.scrbl
  pkgs/racket-doc/scribblings/reference/unsafe-undefined.scrbl
  pkgs/racket-doc/syntax/scribblings/keyword.scrbl
  pkgs/racket-doc/syntax/scribblings/modcode.scrbl
  pkgs/racket-doc/syntax/scribblings/modread.scrbl
  pkgs/racket-doc/syntax/scribblings/readerr.scrbl
  pkgs/racket-doc/syntax/scribblings/struct.scrbl
  pkgs/racket-doc/xml/xml.scrbl
Labels: documentation

#4777 guide: explicitly mention variadic function
  pkgs/racket-doc/scribblings/guide/lambda.scrbl
Labels: documentation, pr:good-to-merge

#4827 Handle get-info errors when getting pkg content.
  pkgs/racket-doc/pkg/scribblings/lib.scrbl
  racket/collects/pkg/lib.rkt
  racket/collects/pkg/private/content.rkt
Labels: pr:good-to-merge
