Repository racket/racket, pull requests merged in 2024-01, with the labels that each got.

#4720 syntax/parse: repairs to contract and error reporting
  racket/collects/syntax/parse/experimental/provide.rkt
  racket/collects/syntax/parse/private/kws.rkt
Labels: pr:wait-for-review

#4807 doc: show value of defthing via #:auto-value
  pkgs/racket-doc/info.rkt
  pkgs/racket-doc/xml/xml.scrbl
Labels: documentation

#4632 match: add support for hash and hash* patterns
  pkgs/racket-doc/scribblings/reference/match-grammar.rkt
  pkgs/racket-doc/scribblings/reference/match-parse.rkt
  pkgs/racket-doc/scribblings/reference/match.scrbl
  pkgs/racket-test/tests/match/hash-table-tests.rkt
  pkgs/racket-test/tests/match/main.rkt
  racket/collects/racket/match/parse.rkt
  racket/collects/racket/match/runtime.rkt
Labels: api design

#4892 Reduce a few dependencies.
  racket/collects/json/main.rkt
  racket/collects/pkg/commands.rkt
  racket/collects/pkg/name.rkt
Labels: pr:good-to-merge

#4893 doc: clarify some `raco setup` APIs
  pkgs/racket-doc/pkg/scribblings/path.scrbl
  pkgs/racket-doc/scribblings/raco/setup.scrbl
Labels: documentation
