Repository racket/racket, pull requests merged in 2025-03, with the labels that each got.

#5222 bc complex exp and log
  pkgs/racket-test-core/tests/racket/number.rktl
  racket/src/bc/src/number.c
Labels: racket-bc

#5229 Bring back tests/racket/test in CI
  .github/scripts/run-racket-tests.sh
Labels: ci

#5236 Do not set time limit for core Racket tests
  .github/scripts/run-racket-tests.sh
Labels: ci

#5231 docs: SHA1 is mandatory for package checksums
  pkgs/racket-doc/pkg/scribblings/pkg.scrbl
Labels: documentation, package system
