Repository racket/racket, pull requests merged in 2025-05, with the labels that each got.

#5244 reference: clarify `datum->syntax` recursive conversion
  pkgs/racket-doc/scribblings/reference/stx-ops.scrbl
Labels: documentation, macro system

#5239 Link to `raco demod` in `raco exe`
  pkgs/racket-doc/scribblings/raco/exe.scrbl
Labels: documentation

#5267 build,ac: use xcode-select to infer SDK paths
  racket/src/ac/sdk_ios.m4
  racket/src/bc/configure
  racket/src/cs/c/configure
Labels: platform:macos, build
