Repository racket/racket, pull requests merged in 2025-01, with the labels that each got.

#5151 Json Representation Customization
  pkgs/racket-doc/json/json.scrbl
  racket/collects/json/main.rkt
Labels: api design

#5103 docs: provide example for the `call/cont` / `call/cc` comparison
  pkgs/racket-doc/scribblings/guide/control.scrbl
Labels: documentation

#5114 [doc]: Clarify `end` behavior in `vector-sort[!]` when set to `#f`
  pkgs/racket-doc/scribblings/reference/vectors.scrbl
Labels: documentation

#5168 Bump action versions in the workflow template from `raco pkg new`
  racket/collects/pkg/private/new.rkt
Labels: package system

#5166 json: add `#:replace-malformed-surrogate?` argument
  pkgs/racket-doc/json/json.scrbl
  pkgs/racket-test/tests/json/json.rkt
  racket/collects/json/main.rkt
Labels: api design

#5184 ci: extract run-racket-tests.sh and run more tests on PR and push
  .github/scripts/run-racket-tests.sh
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push-x86_linux.yml
  .github/workflows/ci-push_macos.yml
  pkgs/net-test/tests/net/git-checkout.rkt
Labels: ci
